// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ0mIr3tPRRmE809P57IlihVp-B8dwqGo',
    appId: '1:164622650388:web:ef5fc548f85acfe3de6b01',
    messagingSenderId: '164622650388',
    projectId: 'notifiymessaging',
    authDomain: 'notifiymessaging.firebaseapp.com',
    storageBucket: 'notifiymessaging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlfm4sQOHZHKLux8m0qqaFsZr8x9bHgc8',
    appId: '1:164622650388:android:9695ae57086ab2f1de6b01',
    messagingSenderId: '164622650388',
    projectId: 'notifiymessaging',
    storageBucket: 'notifiymessaging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQoFPibMiIoKy-zoAPg0QLOPrv5HvVP8',
    appId: '1:164622650388:ios:406180e5df28c7f0de6b01',
    messagingSenderId: '164622650388',
    projectId: 'notifiymessaging',
    storageBucket: 'notifiymessaging.appspot.com',
    iosClientId: '164622650388-p45q96mtlk618qtsqe7lipgeqtocnoka.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQoFPibMiIoKy-zoAPg0QLOPrv5HvVP8',
    appId: '1:164622650388:ios:0798de460c3e98fbde6b01',
    messagingSenderId: '164622650388',
    projectId: 'notifiymessaging',
    storageBucket: 'notifiymessaging.appspot.com',
    iosClientId: '164622650388-qsvmi1rjlfqud9gjaktv3h9tib7d3r4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo.RunnerTests',
  );
}
